INSERT INTO PRODUCT (PRODUCTID ,PRODUCTNAME ,COST ,PRODUCTTYPE ,SCANCODEID)
VALUES(1 ,'PRODUCTNAMEA' ,1000 ,'A' ,'SCANCODEIDA');

INSERT INTO PRODUCT (PRODUCTID ,PRODUCTNAME ,COST ,PRODUCTTYPE ,SCANCODEID)
VALUES(2 ,'PRODUCTNAMEB' ,2000 ,'B' ,'SCANCODEIDB' );

INSERT INTO PRODUCT (PRODUCTID ,PRODUCTNAME ,COST ,PRODUCTTYPE ,SCANCODEID)
VALUES(3 ,'PRODUCTNAMEC' ,3000 ,'C' ,'SCANCODEIDC' );

INSERT INTO PRODUCT (PRODUCTID ,PRODUCTNAME ,COST ,PRODUCTTYPE ,SCANCODEID)
VALUES(4 ,'PRODUCTNAMED' ,1000 ,'D' ,'SCANCODEIDD' );